import type { NextPage } from 'next'
import Head from 'next/head'
import ComingSoon from '../../components/ComingSoon'

const Blog: NextPage = () => {
  return (
    <>
      <Head>
        <title>Blog | Coming Soon</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ComingSoon />
    </>
  )
}

export default Blog
