import { useRef, useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

import Header from '../components/Header'
import Footer from '../components/Footer'

import lottie from 'lottie-web';
import styles from '../styles/Home.module.css'

const Home: any = () => {
  const containerRef = useRef() as React.MutableRefObject<HTMLInputElement>;

  useEffect(() => {
    if(containerRef.current != undefined) {
      lottie.loadAnimation({
        container: containerRef.current, // the dom element that will contain the animation
        renderer: 'svg',
        loop: true,
        autoplay: true,
        path: 'assets/json/lottie.json'
      });
    }
  }, [])
  
  return (
    <div className={styles.home}>
      <Head>
        <title>Welcome to Good Bridging</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <main>
        <section className={styles.hero}>
          <div className={styles.content}>
            <img className={styles.shapes} src="/assets/svg/home-hero-shapes.svg" alt="" />
            <div className={styles.lottie} ref={containerRef}></div>
            {/* <img className={styles.mascot} src="/assets/svg/home-hero-mascot.svg" alt="" /> */}
            <div>
              <h1>Good Morning and Good Bridging!</h1>
              <p>&quot;GM and GB&quot; stands for &quot;Good Morning and Good Bridging&quot;, as every new ERC-20assets cross from Ethereum to avalanche since it&apos;s way faster and cheaper, therefore enhancing the DeFi experience.</p>
            </div>
          </div>
        </section>
        <section className={styles.about} id="about">
          <img className={styles.shapes} src="/assets/svg/home-about-shape.svg" alt="" />
          <div className={styles.content}>
            <img className={styles.mascot} src="/assets/svg/goob_bridging_light_background.svg" alt="" />
            <div>
              <p>What’s $GB?</p>
              <p>Good Bridging Token ($GB) is a fair launched DeFi token in the Avalanche Network, 100% of the supply was airdropped evenly to 16,135 addresses give a warm welcome to those decentralization enthusiasts that have used the Avalanche-Ethereum Bridge to transact their ERC-20 assets in the Avalanche Network.</p>
              <p>No insiders, no pre-sale, no VC’s, no team allocation.</p>
              <img className={styles.banner} src="/assets/svg/home-about-banner.svg" alt="" />
            </div>
          </div>
        </section>
        <div className={styles.ecosystem} id="ecosystem">
          <div className={styles.footer}>
            <h1>People that trusts in GB</h1>
            <div className={styles.images_container}></div>
          </div>
        </div>
        <section className={styles.calendar} id="calendar">
          <table className="content">
            <thead>
              <tr>
                <th colSpan={3}>
                  <div><img src="/assets/svg/home-airdrop-banner-icon.svg" alt="" /> Calendar</div>
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className={styles.date}>
                  <div>12 Oct</div>
                </td>
                <td className={styles.name}>
                  <div>Event Name</div>
                </td>
                <td className={styles.value}>
                  <div>Value</div>
                </td>
              </tr>
              <tr>
                <td className={styles.date}>
                  <div>12 Oct</div>
                </td>
                <td className={styles.name}>
                  <div>Event Name</div>
                </td>
                <td className={styles.value}>
                  <div>Value</div>
                </td>
              </tr>
              <tr>
                <td className={styles.date}>
                  <div>12 Oct</div>
                </td>
                <td className={styles.name}>
                  <div>Event Name</div>
                </td>
                <td className={styles.value}>
                  <div>Value</div>
                </td>
              </tr>
            </tbody>
          </table>
        </section>
        <section className={styles.news} id="blog">
          <div className={styles.header}>
            <h1>Good Bridging News</h1>
            <img src="/assets/svg/home-news-mascot.svg" alt="" />
          </div>
          <div className={styles.content}>
            <div className={styles.left}>
              <img src="/assets/png/home-news-thumbnail.png" alt="" />
              <span>Posted Monday 00, Month, Year</span>
              <h1>Post Title</h1>
              <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod</p>
              <button>Read More</button>
            </div>
            <div className={styles.rigth}>
              <div className={styles.post}>
                <img src="/assets/png/home-news-posts-thumbnail.png" alt="" />
                <div className={styles.post_content}>
                  <span>Posted Monday 00, Month, Year</span>
                  <h1>Post Title</h1>
                  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam</p>
                </div>
              </div>
              <div className={styles.post}>
                <img src="/assets/png/home-news-posts-thumbnail.png" alt="" />
                <div className={styles.post_content}>
                  <span>Posted Monday 00, Month, Year</span>
                  <h1>Post Title</h1>
                  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam</p>
                </div>
              </div>
              <div className={styles.post}>
                <img src="/assets/png/home-news-posts-thumbnail.png" alt="" />
                <div className={styles.post_content}>
                  <span>Posted Monday 00, Month, Year</span>
                  <h1>Post Title</h1>
                  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam</p>
                </div>
              </div>
              <div className={styles.post}>
                <img src="/assets/png/home-news-posts-thumbnail.png" alt="" />
                <div className={styles.post_content}>
                  <span>Posted Monday 00, Month, Year</span>
                  <h1>Post Title</h1>
                  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  )
}

export default Home
